alter table ST_ATMOSPHERIC_GAS add constraint FK_ST_ATMOSPHERIC_GAS_ON_GAS foreign key (GAS_ID) references ST_GAS(ID);
alter table ST_ATMOSPHERIC_GAS add constraint FK_ST_ATMOSPHERIC_GAS_ON_ATMOSPHERE foreign key (ATMOSPHERE_ID) references ST_ATMOSPHERE(ID);
create index IDX_ST_ATMOSPHERIC_GAS_ON_GAS on ST_ATMOSPHERIC_GAS (GAS_ID);
create index IDX_ST_ATMOSPHERIC_GAS_ON_ATMOSPHERE on ST_ATMOSPHERIC_GAS (ATMOSPHERE_ID);
